import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.awt.event.WindowStateListener;

public class GameTarget extends JFrame {

    // Attributes of object
    private JTextPane gameDescription;
    private JPanel rootPane;
    private JLabel gameDescriptionHeadline;

    /**
     * Initializing attributes and JFrame object
     */
    public GameTarget() {
        this.setTitle("Ziel");
        initializeGUI();
        this.setContentPane(rootPane);
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.setResizable(true);

        // Setting GUI elements up
        gameDescriptionHeadline.setFont(HelpDesk.getStandardHeadlineFont());
        gameDescription.setEditable(false);
    }

    private void initializeGUI() {
        GridBagConstraints constraints = new GridBagConstraints();
        constraints.fill = GridBagConstraints.HORIZONTAL;
        constraints.gridheight = 1;
        constraints.gridwidth = 5;
        constraints.gridx = 2;
        constraints.gridy = 0;

        rootPane = new JPanel(new GridBagLayout());
        JLabel headline = new JLabel("Spielziel");
        headline.setFont(HelpDesk.getStandardHeadlineFont());
        rootPane.add(headline, constraints);

        constraints.gridy++;
        constraints.insets = new Insets(20,0,0,0);
        constraints.gridheight = 10;
        constraints.weightx = 1;

        JTextPane content = new JTextPane();
        content.setEditable(false);
        content.setText("In diesem Spiel schlüpfen sie in die Haut eines Lageristen. Hier bekommen sie immer Aufträge " +
                "die sie entweder liefern sollen also auslagern oder müssen neue Produkte einlagern. Falls sie " +
                "Platzprobleme bekommen, können sie Produkte umlagern oder zerstören. Diese Funktionen kosten sie " +
                "allerdings Geld. Für eine Umlagerung müssen sie 100€ bezahlen und für die Zerstörung 500€. Während " +
                "des Spielverlaufes kann auch ein negativer Gesamtbetrag enstehen. Das Spiel ist vorbei, wenn sie " +
                "keine Objekte liefern können, weil die Produkte nicht im Lager sind und keine neuen Aufträge " +
                "beziehen können.");
        rootPane.add(content, constraints);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JScrollPane scrollPane1 = new JScrollPane();
        rootPane = new JPanel();
        rootPane.setLayout(new GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), -1, -1));
        scrollPane1.setViewportView(rootPane);
        gameDescriptionHeadline = new JLabel();
        gameDescriptionHeadline.setText("Spielziel");
        rootPane.add(gameDescriptionHeadline, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        rootPane.add(spacer1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        rootPane.add(spacer2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        gameDescription = new JTextPane();
        gameDescription.setText("In diesem Spiel schlüpfen sie in die Haut eines Lageristen. Hier bekommen sie immer Aufträge die sie entweder liefern sollen also auslagern oder müssen neue Produkte einlagern. Falls sie Platzprobleme bekommen, können sie Produkte umlagern oder zerstören. Diese Funktionen kosten sie allerdings Geld. Für eine Umlagerung müssen sie 100€ bezahlen und für die Zerstörung 500€. Während des Spielverlaufes kann auch ein negativer Gesamtbetrag enstehen. Das Spiel ist vorbei, wenn sie keine Objekte liefern können, weil die Produkte nicht im Lager sind und keine neuen Aufträge beziehen können.");
        rootPane.add(gameDescription, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final Spacer spacer3 = new Spacer();
        rootPane.add(spacer3, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }
}
